### ISSUE TITLE
use systemd module instead of service start

### ISSUE THREAD

**Issue by osmanburucu-ibm** [osmanburucu-ibm/deploy-urbancode-deploy#9]
Actual: for starting the systemd services the service module is used. 
Target: Use systemd instead -> and wait till service starts and eliminate the pause step!

actual example:
```yml
# TODO:use systemd module from ansible!
  - name: start AGENT service
    become: yes
    service:
      name: "{{ ucda_service_name }}"
      enabled: yes
      state: started

# wait so that service is up and running!
  - pause:
      seconds: 30
```

```yml
- name: start AGENT service
  become: yes
  systemd:
    name: "{{ ucda_service_name }}"
    state: started
    enabled: True
    masked: no
```
